# Lesson 16: numpy

In [1]:
import numpy as np

In [2]:
a = np.arange(12, 43)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42])

In [3]:
z = np.zeros(12)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
t = np.arange(9).reshape((3, 3))
t

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
f = np.array([1, 2, 0, 0, 4, 0])
f[f > 0]

array([1, 2, 4])

In [7]:
a = np.ones((5, 3))
b = np.ones((3, 2))

a @ b

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

In [10]:
e = np.ones((10, 10))
e[[0, -1],:] = 0
e[:,[0,-1]] = 0
e

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
r = np.random.random(12)
r.sort()
r

array([0.08162611, 0.23425982, 0.28371661, 0.31162257, 0.40904506,
       0.49901622, 0.52506387, 0.73459264, 0.77173931, 0.79135975,
       0.82543189, 0.86137228])